const himnos = [

    { id: 1, titulo: "Cada momento la vida me da" },
    { id: 2, titulo: "Por fe contemplo redención" },
    { id: 3, titulo: "Nunca desmayes" },
    { id: 4, titulo: "No hay tristeza en el reino" },
    { id: 5, titulo: "Hay un jardín memorable" },
    { id: 6, titulo: "De tal manera me amó" },
    { id: 7, titulo: "Nunca, Dios mío, cesará mi labio" },
    { id: 8, titulo: "Cuando combatido" },
    { id: 9, titulo: "Obediente a tu mandato" },
    { id: 10, titulo: "Caminando con el Señor" },
    { id: 11, titulo: "A Jesucristo ven sin tardar" },
    { id: 12, titulo: "¡Oh, sí, es un Reino aquí!" },
    { id: 13, titulo: "Del santo amor de Cristo" },
    { id: 14, titulo: "Pertenezco a Cristo" },
    { id: 15, titulo: "La gracia de Dios" },
    { id: 16, titulo: "Maravillado estoy" },
    { id: 17, titulo: "El nombre de Jesús" },
    { id: 18, titulo: "Cuando andemos con Dios" },
    { id: 19, titulo: "En el corazón de Dios" },
    { id: 20, titulo: "Padre a tus pies me postro" },
    { id: 21, titulo: "Incansables compañeros" },
    { id: 22, titulo: "Por la mañana" },
    { id: 23, titulo: "Dulce oración" },
    { id: 24, titulo: "Ved la fuente sanadora" },
    { id: 25, titulo: "Hay una iglesia preciosa" },
    { id: 26, titulo: "¡Hermosa tierra Sión!" },
    { id: 27, titulo: "El renuevo" },
    { id: 28, titulo: "Cantaré la bella historia" },
    { id: 29, titulo: "Pronto la noche viene" },
    { id: 30, titulo: "¡Juventud, despertad!" },
    { id: 31, titulo: "Recíbeme cual soy" },
    { id: 32, titulo: "Quiero seguir a mi Jesús" },
    { id: 33, titulo: "Manos redentoras" },
    { id: 34, titulo: "Cantaré‚ a Jesús, de mi alma rey" },
    { id: 35, titulo: "¡A dónde iré?" },
    { id: 36, titulo: "Un nombre nuevo en la gloria" },
    { id: 37, titulo: "Estoy admirado del amor de mi Jesús" },
    { id: 38, titulo: "La luz de Dios" },
    { id: 39, titulo: "Israel restaurado" },
    { id: 40, titulo: "¡Ven, oh pródigo, ven!" },
    { id: 41, titulo: "Hay una senda" },
    { id: 42, titulo: "El anhelo del cristiano" },
    { id: 43, titulo: "¡Sea la paz! ¡Sea la paz!" },
    { id: 44, titulo: "Nadie pudo amarme como Cristo" },
    { id: 45, titulo: "Salid de Egipto ya" },
    { id: 46, titulo: "Somos un cuerpo en Cristo" },
    { id: 47, titulo: "Pies divinos" },
    { id: 48, titulo: "¡Loor a Ti, Señor!" },
    { id: 49, titulo: "¡Ábrele!" },
    { id: 50, titulo: "¡Oh, Cristo mío!" },
    { id: 51, titulo: "¡Oh, jóvenes, venid!" },
    { id: 52, titulo: "Sal a sembrar" },
    { id: 53, titulo: "La voz de Jesús" },
    { id: 54, titulo: "Rostro divino" },
    { id: 55, titulo: "Allá la puerta franca está" },
    { id: 56, titulo: "¡Oh, cuán dulce es fiar en Cristo!" },
    { id: 57, titulo: "Sigue orando" },
    { id: 58, titulo: "Piensa bien lo que hoy vas a hacer" },
    { id: 59, titulo: "Toma mi vida" },
    { id: 60, titulo: "Llamamiento de Cristo" },
    { id: 61, titulo: "La palabra de Dios" },
    { id: 62, titulo: "Escuela Sabática" },
    { id: 63, titulo: "Brille o no el sol" },
    { id: 64, titulo: "¡Salid valientes batallones de Israel!" },
    { id: 65, titulo: "En mi alma hay dulce paz" },
    { id: 66, titulo: "Del culto el tiempo llega" },
    { id: 67, titulo: "Señor, reposamos" },
    { id: 68, titulo: "Roca de la eternidad" },
    { id: 69, titulo: "Embajadores de Jesucristo" },
    { id: 70, titulo: "La siembra" },
    { id: 71, titulo: "¡Oh, qué‚ amigo!" },
    { id: 72, titulo: "Firmes y adelante" },
    { id: 73, titulo: "Cerca de Ti, Señor" },
    { id: 74, titulo: "Dulce comunión" },
    { id: 75, titulo: "¡Paz! ¡Paz! ¡Cuán dulce paz!" },
    { id: 76, titulo: "Cristo es mi dulce Salvador" },
    { id: 77, titulo: "Grande gozo hay en mi alma hoy" },
    { id: 78, titulo: "Tendrás que renacer" },
    { id: 79, titulo: "Entera consagración" },
    { id: 80, titulo: "Santa Biblia" },
    { id: 81, titulo: "Hay un precioso manantial" },
    { id: 82, titulo: "A la siega acudid" },
    { id: 83, titulo: "Ya todo dejé" },
    { id: 84, titulo: "¡Oh, amor de Dios!" },
    { id: 85, titulo: "¡Oh, yo Quiero andar con Cristo!" },
    { id: 86, titulo: "Grandes cosas Cristo ha hecho para mí" },
    { id: 87, titulo: "Sigue a Cristo" },
    { id: 88, titulo: "Dios os guarde" },
    { id: 89, titulo: "El consolador ha venido" },
    { id: 90, titulo: "Puedo oír tu voz llamando" },
    { id: 91, titulo: "Sólo a ti Dios y Señor" },
    { id: 92, titulo: "Cerca, más cerca" },
    { id: 93, titulo: "¡Santo! ¡Santo! ¡Santo!" },
    { id: 94, titulo: "Cuando Él vino a mi corazón" },
    { id: 95, titulo: "¡Guíame, oh, Salvador!" },
    { id: 96, titulo: "Hubo quien por mis culpas muriera" },
    { id: 97, titulo: "Un día Cristo volverá" },
    { id: 98, titulo: "No puede el mundo ser mi hogar" },
    { id: 99, titulo: "Oh, Señor Jesús, dirige" },
    { id: 100, titulo: "A Cristo doy mi canto" },
    { id: 101, titulo: "Cristo está buscando obreros" },
    { id: 102, titulo: "Todo a Cristo yo me rindo" },
    { id: 103, titulo: "Viene otra vez" },
    { id: 104, titulo: "¡Las buenas nuevas!" },
    { id: 105, titulo: "En las aguas de la muerte" },
    { id: 106, titulo: "Feliz, cantando alegre" },
    { id: 107, titulo: "Ama el Pastor sus ovejas" },
    { id: 108, titulo: "Pecador, ven al dulce Jesús" },
    { id: 109, titulo: "Yo quiero trabajar por el Señor" },
    { id: 110, titulo: "La palabra hoy sembrada" },
    { id: 111, titulo: "¡Oh, sí, quiero verle!" },
    { id: 112, titulo: "A solas al huerto" },
    { id: 113, titulo: "Oh, Señor Omnipotente" },
    { id: 114, titulo: "¡Oh, Padre, Eterno Dios!" },
    { id: 115, titulo: "No te dé temor" },
    { id: 116, titulo: "¡Trabajad! ¡Trabajad!" },
    { id: 117, titulo: "Señor, nos recordamos" },
    { id: 118, titulo: "Lejos de mi Padre Dios" },
    { id: 119, titulo: "¡Oh, bondad tan infinita!" },
    { id: 120, titulo: "Yo guiaré" },
    { id: 121, titulo: "Bellas palabras de vida" },
    { id: 122, titulo: "A nuestro Padre Dios" },
    { id: 123, titulo: "Nítido rayo por Cristo" },
    { id: 124, titulo: "Cristo me ama" },
    { id: 125, titulo: "Al amparo de la Roca" },
    { id: 126, titulo: "Dios bendiga las almas unidas" },
    { id: 127, titulo: "En el valle florece la rosa" },
    { id: 128, titulo: "Cristianos Israelitas" },
    { id: 129, titulo: "Alguna vez ya no estaré" },
    { id: 130, titulo: "Hoy es día de reposo" },
    { id: 131, titulo: "Feliz momento" },
    { id: 132, titulo: "Un canto de libertad" },
    { id: 133, titulo: "Mi Rey y mi amigo" },
    { id: 134, titulo: "Cara a cara espero verle" },
    { id: 135, titulo: "¡Piedad, oh, Santo Dios!" },
    { id: 136, titulo: "Loor a Ti, mi Dios, en esta noche" },
    { id: 137, titulo: "Nunca mas tendrás sed" },
    { id: 138, titulo: "De mi tierno Salvador" },
    { id: 139, titulo: "Cuando la trompeta suene" },
    { id: 140, titulo: "¡Oh, gracia excelsa!" },
    { id: 141, titulo: "Da lo mejor al Maestro" },
    { id: 142, titulo: "La mañana vino ya" },
    { id: 143, titulo: "¡Ven a Él, ven a Él!" },
    { id: 144, titulo: "Treinta piezas de plata" },
    { id: 145, titulo: "Dulce consuelo" },
    { id: 146, titulo: "El huerto de oración" },
    { id: 147, titulo: "Es el tiempo de la siega" },
    { id: 148, titulo: "Cristo es el todo" },
    { id: 149, titulo: "En los días de prueba" },
    { id: 150, titulo: "Fuente de vida eterna" },
    { id: 151, titulo: "¡Adoradle!" },
    { id: 152, titulo: "Siempre orad" },
    { id: 153, titulo: "Hoy venimos, cual hermanos" },
    { id: 154, titulo: "Despide hoy tu grey" },
    { id: 155, titulo: "¡Hosanna!" },
    { id: 156, titulo: "El diezmo" },
    { id: 157, titulo: "Jubilosas nuestras voces" },
    { id: 158, titulo: "Más santidad dame" },
    { id: 159, titulo: "Joyas, joyas, joyas" },
    { id: 160, titulo: "Tu dejaste tu trono y corona" },
    { id: 161, titulo: "Cuando lo anhelo más" },
    { id: 162, titulo: "Cansado y triste" },
    { id: 163, titulo: "El Rey que viene" },
    { id: 164, titulo: "Bajo sus alas" },
    { id: 165, titulo: "Manos limpias" },
    { id: 166, titulo: "Me guía Él" },
    { id: 167, titulo: "Soy feliz en el servicio del Señor" },
    { id: 168, titulo: "Jesús en Bethania" },
    { id: 169, titulo: "La segunda venida de Cristo" },
    { id: 170, titulo: "Los diez mandamientos" },
    { id: 171, titulo: "Perdóname, Señor" },
    { id: 172, titulo: "Ya el fin se acerca" },
    { id: 173, titulo: "Te loamos, ¡oh, Dios!" },
    { id: 174, titulo: "Me levantó" },
    { id: 175, titulo: "Bástame su gracia" },
    { id: 176, titulo: "Bendice a tu Creador" },
    { id: 177, titulo: "¡Jerusalén, Jerusalén!" },
    { id: 178, titulo: "Soldados del Señor" },
    { id: 179, titulo: "Yo daré mis diezmos" },
    { id: 180, titulo: "No te dejo solo" },
    { id: 181, titulo: "Mi Dios y yo" },
    { id: 182, titulo: "El mundo feliz" },
    { id: 183, titulo: "Vale la pena servir a Jesús" },
    { id: 184, titulo: "¡Coronadle!" },
    { id: 185, titulo: "Sólo Cristo" },
    { id: 186, titulo: "El reposo de Israel" },
    { id: 187, titulo: "Dulce tu ley" },
    { id: 188, titulo: "Su senda" },
    { id: 189, titulo: "Despliegue el cristiano" },
    { id: 190, titulo: "Mas cual mi Cristo" },
    { id: 191, titulo: "Habla, Señor a mi alma" },
    { id: 192, titulo: "Dejo el mundo" },
    { id: 193, titulo: "Tuyo soy Jesús" },
    { id: 194, titulo: "En el monte Calvario" },
    { id: 195, titulo: "Fiel huésped" },
    { id: 196, titulo: "Ora hasta triunfar" },
    { id: 197, titulo: "Obreros del Señor" },
    { id: 198, titulo: "Jesús es precioso" },
    { id: 199, titulo: "Hay un canto nuevo en mi ser" },
    { id: 200, titulo: "Jehová es mi pastor" },
    { id: 201, titulo: "En medio de las luchas" },
    { id: 202, titulo: "Amigo tengo" },
    { id: 203, titulo: "Corito" },
    { id: 204, titulo: "Oh Cristo mío Rey" },
    { id: 205, titulo: "Canten del amor de Cristo" },
    { id: 206, titulo: "Me guiará mi Salvador" },
    { id: 207, titulo: "Oh qué Salvador" },
    { id: 208, titulo: "Mi padre es un Rey" },
    { id: 209, titulo: "Te loamos" },
    { id: 210, titulo: "Viene otra vez nuestro Salvador" },
    { id: 211, titulo: "Hay quien vele mis pisadas" },
    { id: 212, titulo: "Dulces momentos" },
    { id: 213, titulo: "Roca de los siglos" },
    { id: 214, titulo: "Hazme una fuente" },
    { id: 215, titulo: "Una voz resuena de ansia" },
    { id: 216, titulo: "Quiero seguir las pisadas de Cristo" },
    { id: 217, titulo: "Grato es contar la historia" },
    { id: 218, titulo: "No hay cual Jesús" },
    { id: 219, titulo: "Tierra elegida" },
    { id: 220, titulo: "Tu corazón pide" },
    { id: 221, titulo: "Ignoro yo por que será" },
    { id: 222, titulo: "Habladme más de Cristo" },
    { id: 223, titulo: "Me redimió, Me redimió" },
    { id: 224, titulo: "En tu cena nos juntamos" },
    { id: 225, titulo: "El Señor Jesús está llamando" },
    { id: 226, titulo: "¿Cómo hemos de estar en el juicio?" },
    { id: 227, titulo: "Santo, Santo grande eterno Dios" },
    { id: 228, titulo: "Tengo un amigo" },
    { id: 229, titulo: "Haz lo que quieras de mi" },
    { id: 230, titulo: "Obedezco por fe" },
    { id: 231, titulo: "Pon tu carga en Jesús" },
    { id: 232, titulo: "¡Oh, Cristo, nuestra Roca!" },
    { id: 233, titulo: "Hora de la escuela sabática" },
    { id: 234, titulo: "Dad a Dios inmortal alabanza" },
    { id: 235, titulo: "La tierna voz" },
    { id: 236, titulo: "Mi todo a Dios consagro" },
    { id: 237, titulo: "Lugar hay donde descansar" },
    { id: 238, titulo: "El día santo del Señor" },
    { id: 239, titulo: "A lugares oscuros" },
    { id: 240, titulo: "Hay un lugar do quiero estar" },
    { id: 241, titulo: "Valor y fe" },
    { id: 242, titulo: "Yo soy peregrino" },
    { id: 243, titulo: "Junto a Ti" },
    { id: 244, titulo: "Otro amigo como Cristo no hay" },
    { id: 245, titulo: "Por gracia me levantó" },
    { id: 246, titulo: "Dime la historia de Cristo" },
    { id: 247, titulo: "Gozo da servir a Cristo" },
    { id: 248, titulo: "Estad por Cristo firmes" },
    { id: 249, titulo: "¡Jesús, yo te amo!" },
    { id: 250, titulo: "Cristo fiel te quiero ser" },
    { id: 251, titulo: "Vanidad, todo vanidad" },
    { id: 252, titulo: "Viviendo por fe" },
    { id: 253, titulo: "En su profundo amor" },
    { id: 254, titulo: "El piloto de Galilea" },
    { id: 255, titulo: "El camino de fe" },
    { id: 256, titulo: "Todo en todo es Jesucristo" },
    { id: 257, titulo: "Sagrado es el amor," },
    { id: 258, titulo: "Salmo de la ley - Salmo 19" },
    { id: 259, titulo: "Salmo de oración - Salmo 13" },
    { id: 260, titulo: "Salmo de alabanza - Salmo 100" },
    { id: 261, titulo: "Salmo de alabanza - Salmo 117" },
    { id: 262, titulo: "Salmo de alabanza - Salmo 134" },
    { id: 263, titulo: "Salmo de esperanza - Salmo 121" },
    { id: 264, titulo: "Salmo de inspiración - Salmo 123" },
    { id: 265, titulo: "Salmo de esperanza - Salmo 126" },
    { id: 266, titulo: "Salmo de alabanza - Salmo 150" },
    { id: 267, titulo: "Salmo de la misericordia - Salmo 136" },
    { id: 268, titulo: "Salmo de esperanza - Salmo 23" },
    { id: 269, titulo: "Él me sostendrá" },
    { id: 270, titulo: "Con voz benigna" },
    { id: 271, titulo: "Historia de gracia y amor" },
    { id: 272, titulo: "Id, Id por el mundo" },
    { id: 273, titulo: "Abre mis ojos a la luz" },
    { id: 274, titulo: "Sálvame, oh Dios, de toda tentación" },
    { id: 275, titulo: "Huye cual ave a tu monte" },
    { id: 276, titulo: "Indigno soy" },
    { id: 277, titulo: "La tumba le encerró" },
    { id: 278, titulo: "De mi tristeza" },
    { id: 279, titulo: "¡Oh, Señor! Procuro en vano" },
    { id: 280, titulo: "Brilla en tu lugar" },
    { id: 281, titulo: "Al Cristo vivo sirvo" },
    { id: 282, titulo: "Años mi alma en vanidad vivió" },
    { id: 283, titulo: "Si fui motivo de dolor Señor" },
    { id: 284, titulo: "Tentado, no cedas" },
    { id: 285, titulo: "Obrero en la mies de Cristo" },
    { id: 286, titulo: "Digno es el Cordero" },
    { id: 287, titulo: "Junto a mi Dios" },
    { id: 288, titulo: "¿Quieres sobre el mundo ser un vencedor?" },
    { id: 289, titulo: "Comprado con sangre por Cristo" },
    { id: 290, titulo: "Día de gran libertad" },
    { id: 291, titulo: "Nada de sombras" },
    { id: 292, titulo: "Si yo gano al mundo" },
    { id: 293, titulo: "Cuán grande es Él" },
    { id: 294, titulo: "Un ancla tenemos" },
    { id: 295, titulo: "Un día" },
    { id: 296, titulo: "No se ha dicho aun la mitad" },
    { id: 297, titulo: "Me hirió el pecado" },
    { id: 298, titulo: "En mis angustias" },
    { id: 299, titulo: "Mi pastor es Jesús" },
    { id: 300, titulo: "¿Respuesta no hay?" },
    { id: 301, titulo: "No me pases, no me olvides" },
    { id: 302, titulo: "¿Quién a Cristo quiere?" },
    { id: 303, titulo: "Del amor divino" },
    { id: 304, titulo: "Maravillosa gracia" },
    { id: 305, titulo: "Yo sólo espero ese día" },
    { id: 306, titulo: "En los negocios del Rey" },
    { id: 307, titulo: "El placer de mi alma" },
    { id: 308, titulo: "Firme estaré" },
    { id: 309, titulo: "La voluntad de Dios" },
    { id: 310, titulo: "La vid y los pámpanos" },
    { id: 311, titulo: "Más profundo amor" },
    { id: 312, titulo: "Confío en Dios" },
    { id: 313, titulo: "El piloto es mi Jesús" },
    { id: 314, titulo: "Pertenezco a mi Rey" },
    { id: 315, titulo: "Yo soy soldado de Jesús" },
    { id: 316, titulo: "A tu lado quiero andar Señor" },
    { id: 317, titulo: "Ojos divinos" },
    { id: 318, titulo: "De tu Espíritu divino" },
    { id: 319, titulo: "Nos veremos en el río" },
    { id: 320, titulo: "Aviva tu obra, oh Dios" },
    { id: 321, titulo: "Un mensaje del Señor" },
    { id: 322, titulo: "Mi Redentor, el Rey de gloria" },
    { id: 323, titulo: "A los pies de Jesucristo" },
    { id: 324, titulo: "Gloria sin fin" },
    { id: 325, titulo: "Oh, ven sin tardar" },
    { id: 326, titulo: "Cuán felices fuimos" },
    { id: 327, titulo: "De Jesús el nombre guarda" },
    { id: 328, titulo: "Cristianos todos ya prepararse" },
    { id: 329, titulo: "¿Eres limpio en la sangre?" },
    { id: 330, titulo: "Oh, Roca Eterna" },
    { id: 331, titulo: "Salvador mío, como Tú eres" },
    { id: 332, titulo: "Siervos de Jesús" },
    { id: 333, titulo: "La peña fuerte" },
    { id: 334, titulo: "Mas cerca de Cristo" },
    { id: 335, titulo: "En la mañana" },
    { id: 336, titulo: "Iré si Él va conmigo" },
    { id: 337, titulo: "Muy cercano está el día" },
    { id: 338, titulo: "A su nombre gloria" },
    { id: 339, titulo: "Canta, oh buen cristiano" },
    { id: 340, titulo: "Pon tu todo en su altar" },
    { id: 341, titulo: "En la cruenta cruz" },
    { id: 342, titulo: "Ven amigo a Jesús" },
    { id: 343, titulo: "Soy la triste oveja" },
    { id: 344, titulo: "Toma de la fuente de agua viva" },
    { id: 345, titulo: "Canto aleluya, gloria a Dios" },
    { id: 346, titulo: "Sólo en Jesús" },
    { id: 347, titulo: "Bellas mansiones" },
    { id: 348, titulo: "El día perfecto" },
    { id: 349, titulo: "Guardia de oración" },
    { id: 350, titulo: "Valientes pregoneros" },
    { id: 351, titulo: "Óyenos, te lo rogamos" },
    { id: 352, titulo: "Visión pastoral" },
    { id: 353, titulo: "Clamo a ti, Señor" },
    { id: 354, titulo: "Israel de Dios" },
    { id: 355, titulo: "Obreros de Dios y de Cristo" },
    { id: 356, titulo: "Divino compañero" },
    { id: 357, titulo: "Venid... Id a predicar" },
    { id: 358, titulo: "Honra, gloria y loor ¡Tuya es, oh Señor!" },
    { id: 359, titulo: "Cristo es la Peña de Horeb" },
    { id: 360, titulo: "Reunidos" },
    { id: 361, titulo: "Jerusalén, Dios te ama y te reunirá" },
    { id: 362, titulo: "Cristo me halló" },
    { id: 363, titulo: "Lo entenderemos" },
    { id: 364, titulo: "Señor, tu día pasa" },
    { id: 365, titulo: "El día del Señor" },
    { id: 366, titulo: "Salmo 24:7-10" },
    { id: 367, titulo: "Obreros en la viña" },
    { id: 368, titulo: "Sublime don" },
    { id: 369, titulo: "Pero queda Cristo" },
    { id: 370, titulo: "La santa cena" },
    { id: 371, titulo: "Nada sé sobre el futuro" },
    { id: 372, titulo: "La Iglesia de Dios, novia del Cordero" },
    { id: 373, titulo: "¡Oh que inmenso gozo!" },
    { id: 374, titulo: "Meditar en Jesús" },
    { id: 375, titulo: "El fin de nuestra jornada" },
    { id: 376, titulo: "Arrolladas las neblinas" },
    { id: 377, titulo: "Nada puede ya faltarme" },
    { id: 378, titulo: "Lluvias de gracia" },
    { id: 379, titulo: "Dicha grande" },
    { id: 380, titulo: "La cruz no es mayor" },
    { id: 381, titulo: "¡Cristo, mi piloto sé!" },
    { id: 382, titulo: "¿Que me puede dar perdón?" },
    { id: 383, titulo: "Todo debo a Él" },
    { id: 384, titulo: "Ven, gran libertador" },
    { id: 385, titulo: "Dios es amor" },
    { id: 386, titulo: "Alabadle" },
    { id: 387, titulo: "¿Quién está por Cristo?" },
    { id: 388, titulo: "Tesoro incomparable" },
    { id: 389, titulo: "Hay vida en mirar" },
    { id: 390, titulo: "¿Te hallas listo?" },
    { id: 391, titulo: "Sí viene" },
    { id: 392, titulo: "La mañana de oro" },
    { id: 393, titulo: "Haticva (Hebreo) - La esperanza (Español)" },
    { id: 394, titulo: "Jerusalén" },
    { id: 395, titulo: "Alabad al gran Rey" },
    { id: 396, titulo: "Ante el trono de tu gracia" },
    { id: 397, titulo: "Salmo 32" },
    { id: 398, titulo: "Salmo 93" },
    { id: 399, titulo: "Salmo 128" },
    { id: 400, titulo: "Blancos vestidos" }


];

// Esperar a que el DOM esté completamente cargado
document.addEventListener('DOMContentLoaded', function() {
    console.log("DOM cargado, iniciando Himnario.js");
    console.log("Total de himnos disponibles:", himnos.length);
    
    // Referencias al DOM
    const listaHimnos = document.getElementById("lista-himnos");
    const buscarInput = document.getElementById("buscar");
    const buscadorForm = document.getElementById("buscador");

    // Verificar que los elementos del DOM existen
    if (!listaHimnos) {
        console.error("Error: No se encontró el elemento 'lista-himnos'");
    }
    if (!buscarInput) {
        console.error("Error: No se encontró el elemento 'buscar'");
    }
    if (!buscadorForm) {
        console.error("Error: No se encontró el elemento 'buscador'");
    }
    
    if (!listaHimnos || !buscarInput || !buscadorForm) {
        console.error("Error: No se encontraron algunos elementos del DOM necesarios");
        return;
    }
    
    console.log("Todos los elementos del DOM encontrados correctamente");

    // Función para mostrar himnos
    function mostrarHimnos(filtro = "") {
        try {
            console.log("Mostrando himnos con filtro:", filtro);
            listaHimnos.innerHTML = "";
            const terminoBusqueda = filtro.toLowerCase().trim();

            const himnosFiltrados = himnos.filter(himno =>
                himno.titulo.toLowerCase().includes(terminoBusqueda) ||
                himno.id.toString().includes(terminoBusqueda)
            );

            console.log("Himnos filtrados:", himnosFiltrados.length);

            if (himnosFiltrados.length === 0) {
                listaHimnos.innerHTML = `
                    <li class="text-center p-4 text-gray-500">
                        No se encontraron himnos que coincidan con "${filtro}"
                    </li>`;
                return;
            }

            himnosFiltrados.forEach(himno => {
                const li = document.createElement("li");
                li.className = "bg-white p-3 rounded shadow hover:bg-gray-100 transition mb-2";
                
                // Usar ruta absoluta desde la raíz del sitio
                li.innerHTML = `
                    <a href="/iglesia/vistas/visitas/himno.php?id=${himno.id}" class="block">
                        <span class="font-semibold">${himno.id}.</span> ${himno.titulo}
                    </a>`;
                
                listaHimnos.appendChild(li);
            });
            
            console.log("Himnos mostrados exitosamente");
        } catch (error) {
            console.error("Error al mostrar los himnos:", error);
            listaHimnos.innerHTML = `
                <li class="text-center p-4 text-red-500">
                    Error al cargar los himnos. Por favor, recarga la página.
                </li>`;
        }
    }

    // Prevenir envío del formulario de búsqueda
    buscadorForm.addEventListener("submit", function(e) {
        e.preventDefault();
        mostrarHimnos(buscarInput.value);
    });

    // Escuchar búsqueda
    buscarInput.addEventListener("input", (e) => {
        mostrarHimnos(e.target.value);
    });

    // Inicializar lista
    mostrarHimnos();
});
